/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package groovy.gradle.intro

class App {

    String getGreeting(String[] args) {
        return 'Hello ' + args[0];
    }

    static void main(String[] args) {
        println(getGreeting(args));
    }
}
