/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package groovy.gradle.intro

import spock.lang.Specification

class AppTest extends Specification {
    def "application has a greeting"() {
        setup:
        def app = new App()

        when:
        def result = app.getGreeting(new String[]{"jack"})

        then:
        result.equals("Hello jack");
    }
}

